#ifndef NGX_HTTP_SERVER_GUARD_PROCESS_H
#define NGX_HTTP_SERVER_GUARD_PROCESS_H

#define SERVER_OVERLOAD 0
#define SERVER_NOTOVERLOAD 1


int check_overload();

#endif /*NGX_HTTP_SERVER_GUARD_PROCESS_H*/